name: java-app
run-name: java-app workflow
on:
    push:
      paths:
        - 'java-demo/**'
        - '.github/workflows/java-app.yml'
jobs:
  action-environment-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      - name: java-app Test run
        run: | 
          date
          ls -la
          pwd 
          echo "CIAO---------------------------------"
          env
      - run: mvn -version
      - run: java -version