name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  action-environment-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      - name: Test run
      run: | 
          date
          ls -la
          pwd 
          echo "CIAO---------------------------------"
          env
      - run: npm install --global surge
      - run: surge --version
      - run: date >> README.md
      - run: npm install
        working-direciory: ./web-frontend/testingtt/
      - run: npm run build
        working-direciory: ./web-frontend/testingtt/  
      - name: Surge Deploy
      working-direciory: ./web-frontend/testingtt/
       run: | 
          export SURGE_TOKEN=cdc64241c95e91b0b2649ccccb68a643
          surge . upset-color.surge.sh
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"
